image: nixos/unstable
packages:
  - nixos.clang
  - nixos.html-minifier
  - nixos.neocities-cli
  - nixos.pkg-config
  - nixos.ruby
  - nixos.rubyPackages.bigdecimal
  - nixos.sass
environment:
  repo: blue-pits
sources:
  - https://git.sr.ht/~stfn/blue-pits
secrets:
  - 3bb58dc0-1be8-4ac7-bc14-597027defe65 # neocities
tasks:
  - build: |
      cd $repo
      sh build.sh
