image: alpine/edge
packages:
  - ruby-dev
  - nodejs
environment:
  repo: blue-pits
sources:
  - https://git.sr.ht/~stfn/blue-pits
secrets:
  - 3bb58dc0-1be8-4ac7-bc14-597027defe65 # neocities 
tasks:
  - setup: |
      sudo gem install --no-document bundler neocities
  - build: |
      cd $repo
      sh ./build-jekyll
  - deploy: |
      cd $repo
      sh ./deploy-neocities $repo _site
