image: nixos/latest
packages:
  - ruby-dev
  - nodejs
  - npm
environment:
  repo: blue-pits
sources:
  - https://git.sr.ht/~stfn/blue-pits
secrets:
  - 3bb58dc0-1be8-4ac7-bc14-597027defe65 # neocities
tasks:
  - build: |
      nix-shell
      sh build.sh