image: nixos/latest
packages:
  - nixos.bundler
  - nixos.ruby_3_2
  - nixos.nodejs_20
  - nixos.nodePackages_latest.npm
  - nixos.nodePackages_latest.html-minifier
environment:
  repo: blue-pits
sources:
  - https://git.sr.ht/~stfn/blue-pits
secrets:
  - 3bb58dc0-1be8-4ac7-bc14-597027defe65 # neocities
tasks:
  - build: |
      sh build.sh