url: "https://bluepitshousingaction.co.uk"

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-toc

collections:
  pages:
    output: true
    permalink: /:name/

exclude:
  - build
  - shell.nix
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - bin/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
