url: "https://bluepitshousingaction.co.uk"

plugins:
  - jekyll-sitemap
  - jekyll-minifier

collections:
  pages:
    output: true
    permalink: /:name/

exclude:
  - build-jekyll
  - deploy-neocities
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
